import { DepartmentRole, ScriptLine, Cue } from "@/lib/types";

export const DEPARTMENT_COLORS: Record<DepartmentRole, string> = {
  director: "#f97316",
  lighting: "#eab308",
  sound: "#3b82f6",
  stage_left: "#ef4444",
  stage_right: "#22c55e",
  stage_crew: "#06b6d4",
};

export const PRESET_MESSAGES = [
  "Stand by",
  "Go now",
  "Hold",
  "Repeat cue",
  "Need confirmation",
  "Reset to last mark",
] as const;

export const SAMPLE_SCRIPT_LINES: ScriptLine[] = [
  { id: 1, actNumber: 1, lineNumber: 1, character: "Stage Direction", text: "House to half. Projection clocks begin drifting in opposite directions.", sceneSeparator: "The Library of Broken Clocks" },
  { id: 2, actNumber: 1, lineNumber: 2, character: "Ari", text: "Why do all the clocks here tick at different speeds?" },
  { id: 3, actNumber: 1, lineNumber: 3, character: "Caretaker Ibis", text: "Because truth never arrives all at once." },
  { id: 4, actNumber: 1, lineNumber: 4, character: "Stage Direction", text: "A brass ladder rolls downstage. Dust motes sharpen in warm side light." },
  { id: 5, actNumber: 1, lineNumber: 5, character: "Ari", text: "If I rewind one, can I undo today?" },
  { id: 6, actNumber: 1, lineNumber: 6, character: "Caretaker Ibis", text: "You can undo an hour. The hour will remember." },
  { id: 7, actNumber: 1, lineNumber: 7, character: "Stage Direction", text: "Bell chime motif, three notes. Trapdoor panel unlocks upstage center.", sceneSeparator: "Down the Spiral" },
  { id: 8, actNumber: 1, lineNumber: 8, character: "Ari", text: "This stair is impossible. It goes down and up at once." },
  { id: 9, actNumber: 1, lineNumber: 9, character: "Mirror Twin", text: "Only if you insist on choosing one direction." },
  { id: 10, actNumber: 1, lineNumber: 10, character: "Ari", text: "Who are you?" },
  { id: 11, actNumber: 1, lineNumber: 11, character: "Mirror Twin", text: "The answer you keep avoiding." },
  { id: 12, actNumber: 1, lineNumber: 12, character: "Stage Direction", text: "Stair projection rotates ninety degrees. Ensemble crosses with lantern canes." },
  { id: 13, actNumber: 1, lineNumber: 13, character: "Stage Direction", text: "Transition to tea table preset. Cups fly in on monofilament line.", sceneSeparator: "Tea at Impossible O'Clock" },
  { id: 14, actNumber: 1, lineNumber: 14, character: "Host Finch", text: "Sit. Stand. Sit again. The table prefers indecision." },
  { id: 15, actNumber: 1, lineNumber: 15, character: "Ari", text: "Do any of you answer straight?" },
  { id: 16, actNumber: 1, lineNumber: 16, character: "Host Finch", text: "Straight lines are for railroads and rulers." },
  { id: 17, actNumber: 1, lineNumber: 17, character: "Card Guard", text: "By decree, no one may leave before the last pour." },
  { id: 18, actNumber: 1, lineNumber: 18, character: "Stage Direction", text: "End of act image: cups freeze midair. Slow blackout on Ari." },

  { id: 19, actNumber: 2, lineNumber: 1, character: "Stage Direction", text: "Interval restart. Forest gobos sweep in. Low fog at ankle height.", sceneSeparator: "The Orchard of Signs" },
  { id: 20, actNumber: 2, lineNumber: 2, character: "Ari", text: "Every signpost points to a different place named Here." },
  { id: 21, actNumber: 2, lineNumber: 3, character: "Guide Pica", text: "That is because 'here' is a moving target." },
  { id: 22, actNumber: 2, lineNumber: 4, character: "Ari", text: "Then how do I find the court?" },
  { id: 23, actNumber: 2, lineNumber: 5, character: "Guide Pica", text: "Follow the loudest silence." },
  { id: 24, actNumber: 2, lineNumber: 6, character: "Stage Direction", text: "Three signposts revolve independently; arrowheads glow cobalt." },
  { id: 25, actNumber: 2, lineNumber: 7, character: "Stage Direction", text: "Hard cut to courtroom. Bench rolls in from stage left.", sceneSeparator: "The Court of Red Ink" },
  { id: 26, actNumber: 2, lineNumber: 8, character: "Chancellor Red", text: "Case seven: the theft of one future afternoon." },
  { id: 27, actNumber: 2, lineNumber: 9, character: "Ari", text: "You cannot steal an afternoon." },
  { id: 28, actNumber: 2, lineNumber: 10, character: "Chancellor Red", text: "Then explain why no one reached sunset yesterday." },
  { id: 29, actNumber: 2, lineNumber: 11, character: "Witness Bell", text: "At four forty-three, all shadows stood still." },
  { id: 30, actNumber: 2, lineNumber: 12, character: "Stage Direction", text: "Ink spill projection crawls from upstage to apron." },
  { id: 31, actNumber: 2, lineNumber: 13, character: "Stage Direction", text: "Court walls split. Archive shelves rise behind.", sceneSeparator: "Records Room" },
  { id: 32, actNumber: 2, lineNumber: 14, character: "Archivist Glass", text: "Here are the entries that were rewritten in your hand." },
  { id: 33, actNumber: 2, lineNumber: 15, character: "Ari", text: "I never wrote these." },
  { id: 34, actNumber: 2, lineNumber: 16, character: "Mirror Twin", text: "Not yet. But you will, if you keep denying me." },
  { id: 35, actNumber: 2, lineNumber: 17, character: "Ari", text: "Then I choose differently now." },
  { id: 36, actNumber: 2, lineNumber: 18, character: "Stage Direction", text: "Act break sting: all clocks strike thirteen, then silence." },

  { id: 37, actNumber: 3, lineNumber: 1, character: "Stage Direction", text: "Pre-dawn blue. Bare stage except one suspended pendulum.", sceneSeparator: "The Pendulum Bridge" },
  { id: 38, actNumber: 3, lineNumber: 2, character: "Ari", text: "If I cross, I lose the map I've been following." },
  { id: 39, actNumber: 3, lineNumber: 3, character: "Caretaker Ibis", text: "Good. Maps are for places that do not move." },
  { id: 40, actNumber: 3, lineNumber: 4, character: "Ari", text: "And what is this place, then?" },
  { id: 41, actNumber: 3, lineNumber: 5, character: "Caretaker Ibis", text: "A rehearsal for honesty." },
  { id: 42, actNumber: 3, lineNumber: 6, character: "Stage Direction", text: "Pendulum slows by visible increments until it rests." },
  { id: 43, actNumber: 3, lineNumber: 7, character: "Stage Direction", text: "Bridge clears to open square. Warm practicals bloom.", sceneSeparator: "Morning Square" },
  { id: 44, actNumber: 3, lineNumber: 8, character: "Host Finch", text: "No riddles today. Ask directly." },
  { id: 45, actNumber: 3, lineNumber: 9, character: "Ari", text: "Will time forgive what I tried to erase?" },
  { id: 46, actNumber: 3, lineNumber: 10, character: "Guide Pica", text: "Time is not a judge. Only a witness." },
  { id: 47, actNumber: 3, lineNumber: 11, character: "Mirror Twin", text: "Say my name and we can walk as one." },
  { id: 48, actNumber: 3, lineNumber: 12, character: "Ari", text: "Ari, before and after. I accept both." },
  { id: 49, actNumber: 3, lineNumber: 13, character: "Stage Direction", text: "Final reveal: every clock face aligns to one shared beat.", sceneSeparator: "Curtain Call Tableau" },
  { id: 50, actNumber: 3, lineNumber: 14, character: "Ensemble", text: "Count not what was lost, but what was learned in counting." },
  { id: 51, actNumber: 3, lineNumber: 15, character: "Chancellor Red", text: "Case dismissed. Future afternoon returned." },
  { id: 52, actNumber: 3, lineNumber: 16, character: "Ari", text: "Then let the city keep its sunset." },
  { id: 53, actNumber: 3, lineNumber: 17, character: "Stage Direction", text: "Music rises. Bows begin on center beat three." },
  { id: 54, actNumber: 3, lineNumber: 18, character: "Stage Direction", text: "House to full over applause. Curtain out." },
];

export const SAMPLE_CUES: Cue[] = [
  { id: "cue-1", lineId: 1, anchorWordStart: 0, anchorWordEnd: 2, department: "sound", text: "Clock drone bed in at -20dB", standbyOffsetMs: 6000, goOffsetMs: 0 },
  { id: "cue-2", lineId: 1, anchorWordStart: 4, anchorWordEnd: 6, department: "lighting", text: "Projection clocks on cyc, slow drift", standbyOffsetMs: 5000, goOffsetMs: 0 },
  { id: "cue-3", lineId: 4, anchorWordStart: 0, anchorWordEnd: 3, department: "stage_crew", text: "Roll brass ladder to DS-center mark", standbyOffsetMs: 4500, goOffsetMs: 0 },
  { id: "cue-4", lineId: 7, anchorWordStart: 0, anchorWordEnd: 3, department: "sound", text: "Bell motif: 3-note hit", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-5", lineId: 7, anchorWordStart: 5, anchorWordEnd: 7, department: "stage_left", text: "Unlock trap panel US-center", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-6", lineId: 12, anchorWordStart: 0, anchorWordEnd: 2, department: "lighting", text: "Rotate stair projection 90 degrees", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-7", lineId: 13, anchorWordStart: 2, anchorWordEnd: 4, department: "stage_right", text: "Tea table preset glide in from SR", standbyOffsetMs: 5000, goOffsetMs: 0 },
  { id: "cue-8", lineId: 18, anchorWordStart: 2, anchorWordEnd: 4, department: "lighting", text: "Freeze cups practical, slow blackout", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-9", lineId: 19, anchorWordStart: 0, anchorWordEnd: 2, department: "stage_crew", text: "Low fog at 25% across apron", standbyOffsetMs: 6000, goOffsetMs: 0 },
  { id: "cue-10", lineId: 24, anchorWordStart: 1, anchorWordEnd: 3, department: "lighting", text: "Signposts cobalt edge at 70%", standbyOffsetMs: 2500, goOffsetMs: 0 },
  { id: "cue-11", lineId: 25, anchorWordStart: 0, anchorWordEnd: 2, department: "stage_left", text: "Court bench roll in from SL", standbyOffsetMs: 4000, goOffsetMs: 0 },
  { id: "cue-12", lineId: 30, anchorWordStart: 0, anchorWordEnd: 2, department: "sound", text: "Ink hiss sweep L→R", standbyOffsetMs: 2200, goOffsetMs: 0 },
  { id: "cue-13", lineId: 31, anchorWordStart: 0, anchorWordEnd: 1, department: "stage_left", text: "Remove tables and chairs for archive preset", standbyOffsetMs: 5000, goOffsetMs: 0 },
  { id: "cue-13b", lineId: 32, anchorWordStart: 0, anchorWordEnd: 1, department: "stage_right", text: "Split court walls to reveal archive", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-14", lineId: 36, anchorWordStart: 4, anchorWordEnd: 6, department: "sound", text: "All clocks strike thirteen", standbyOffsetMs: 3500, goOffsetMs: 0 },
  { id: "cue-15", lineId: 37, anchorWordStart: 0, anchorWordEnd: 2, department: "lighting", text: "Pre-dawn blue wash 30%", standbyOffsetMs: 4500, goOffsetMs: 0 },
  { id: "cue-16", lineId: 42, anchorWordStart: 0, anchorWordEnd: 2, department: "stage_crew", text: "Pendulum brake to full stop", standbyOffsetMs: 3000, goOffsetMs: 0 },
  { id: "cue-17", lineId: 43, anchorWordStart: 1, anchorWordEnd: 3, department: "lighting", text: "Warm square practical bloom", standbyOffsetMs: 4000, goOffsetMs: 0 },
  { id: "cue-18", lineId: 49, anchorWordStart: 0, anchorWordEnd: 3, department: "sound", text: "Shared heartbeat pulse under reveal", standbyOffsetMs: 3200, goOffsetMs: 0 },
  { id: "cue-19", lineId: 53, anchorWordStart: 0, anchorWordEnd: 2, department: "sound", text: "Curtain-call band track up -12dB", standbyOffsetMs: 4000, goOffsetMs: 0 },
  { id: "cue-20", lineId: 54, anchorWordStart: 0, anchorWordEnd: 2, department: "lighting", text: "House to full over applause", standbyOffsetMs: 3000, goOffsetMs: 0 },
];
